services:
  translator:
    build: .
    container_name: translator
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
    restart: unless-stopped
    mem_limit: 512m
    cpus: 0.50
