services:
  translator:
    build: .
    container_name: translator
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.50"
        reservations:
          memory: 256m
